### PR TITLE
DEP PHP Support in CMS5

### PR DESCRIPTION
**Pull request by sabina-talipova**
## Parent issue
- https://github.com/silverstripe/silverstripe-framework/issues/10402

### CODE REVIEW

**Comment by sabina-talipova** [comment]
Requires 
- https://github.com/silverstripe/silverstripe-widgets/pull/193

**Comment by sabina-talipova** [comment]
Requires to merge first
- https://github.com/silverstripe/silverstripe-spamprotection/pull/88

**Comment by emteknetnz** [comment]
Requires https://github.com/silverstripe/silverstripe-frameworktest/pull/135 to be merged first

**Comment by emteknetnz** [comment]
Requires https://github.com/silverstripe/silverstripe-spamprotection/pull/89

**Review by GuySartorelli — APPROVED** [review]
Wow, we're keeping widgets? That's gonna be one of the first to go once we have a good process for dropping support for modules.

Note for anyone looking at this: We are dropping support for akismet.

**Pull request merged**
